### ISSUE TITLE
Can't enable on blender 3.1.2

### ISSUE THREAD

**Issue by headassbtw** [Protinon/Blender-rpc#15]
As the title says, it throws an error when I enable it on 3.1.2
running arch linux, here's the console log:

```Read prefs: /home/headass/.config/blender/3.1/config/userpref.blend
Exception in module register(): /home/headass/.config/blender/3.1/scripts/addons/Blender-rpc/__init__.py
Traceback (most recent call last):
  File "/usr/share/blender/3.1/scripts/modules/addon_utils.py", line 387, in enable
    mod.register()
  File "/home/headass/.config/blender/3.1/scripts/addons/Blender-rpc/__init__.py", line 42, in register
    rpcConn.connect()
  File "/home/headass/.config/blender/3.1/scripts/addons/Blender-rpc/pypresence/pypresence/presence.py", line 41, in connect
    self.loop.run_until_complete(self.handshake())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/headass/.config/blender/3.1/scripts/addons/Blender-rpc/pypresence/pypresence/baseclient.py", line 122, in handshake
    self.sock_reader, self.sock_writer = await asyncio.open_unix_connection(self.ipc_path, loop=self.loop)
  File "/usr/lib/python3.10/asyncio/streams.py", line 97, in open_unix_connection
    transport, _ = await loop.create_unix_connection(
TypeError: _UnixSelectorEventLoop.create_unix_connection() got an unexpected keyword argument 'loop'
```

**Comment by Protinon** [comment]
Looks to be caused by this issue in PyPresence: https://github.com/qwertyquerty/pypresence/issues/145

Can you try the fix mentioned in that issue? The file mentioned in that issue should be located in `/home/headass/.config/blender/3.1/scripts/addons/Blender-rpc/pypresence/pypresence/baseclient.py`

**Comment by headassbtw** [comment]
yep! that seems to have fixed it, the plugin enables and it shows in discord as well, thanks!
