### ISSUE TITLE
Blender-rpc v1.2.0 breaks when enabled with Discord fully closed

### ISSUE THREAD

**Issue by BluWizard10** [Protinon/Blender-rpc#20]
Installed and functions fine, however, if you attempt to enable Blender-rpc **while Discord is closed**, it will throw this traceback Error...
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.1\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\reece\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Blender-rpc\__init__.py", line 20, in <module>
    rpcConn = rpc.Presence("674448359850901546")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\reece\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Blender-rpc\pypresence\pypresence\presence.py", line 13, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\reece\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\Blender-rpc\pypresence\pypresence\baseclient.py", line 28, in __init__
    raise DiscordNotFound
Blender-rpc.pypresence.pypresence.exceptions.DiscordNotFound: Could not find Discord installed and running on this machine.
```

Additionally, if you attempt to open Blender with this addon previously enabled **while Discord is fully closed**, it will cause Blender to hang and potentially crash!!

Tested with Blender 4.1.

**Comment by Protinon** [comment]
I was able to replicate this error pretty easily. I just [pushed a new release](https://github.com/Protinon/Blender-rpc/releases/tag/v1.3.0) that should handle all edge cases when connecting to Discord.

I'm 95% sure this fixes your issue (and any other connection-related issues), so I'm closing this. But feel free to re-open if you continue experiencing problems. Unless it's a different problem. Then open another issue :)

**Comment by BluWizard10** [comment]
v1.3.0 seemed to have fixed this problem. Thanks!
